apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-app-deployment
  labels:
    app: health-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: health-app
  template:
    metadata:
      labels:
        app: health-app
    spec:
      volumes:
        - name: tomcat-conf
          emptyDir: {}   # <-- volume temporaire pour Tomcat
      containers:
        - name: health-app
          image: health_app-hapi-fhir:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080  # <-- Tomcat écoute sur 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://hapi-fhir-postgres:5432/hapi
            - name: SPRING_DATASOURCE_USERNAME
              value: admin
            - name: SPRING_DATASOURCE_PASSWORD
              value: admin
          volumeMounts:
            - mountPath: /usr/local/tomcat/conf/Catalina/localhost
              name: tomcat-conf
          readinessProbe:
            httpGet:
              path: /fhir/metadata
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /fhir/metadata
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10