apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-app-deployment
  labels:
    app: health-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: health-app
  template:
    metadata:
      labels:
        app: health-app
    spec:
      containers:
        - name: health-app
          image: hapi-fhir:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://hapi-fhir-postgres:5432/hapi
            - name: SPRING_DATASOURCE_USERNAME
              value: admin
            - name: SPRING_DATASOURCE_PASSWORD
              value: admin
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
          readinessProbe:
            httpGet:
              path: /fhir/metadata
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 10
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: /fhir/metadata
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 15
            failureThreshold: 5