global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'kubernetes-nodes'
    static_configs:
      - targets: ['kube-proxy:8001']
    metrics_path: /api/v1/nodes/minikube/proxy/metrics/resource

  - job_name: 'kubernetes-cadvisor'
    static_configs:
      - targets: ['kube-proxy:8001']
    metrics_path: /api/v1/nodes/minikube/proxy/metrics/cadvisor

  - job_name: 'hapi-fhir'
    static_configs:
      - targets: ['kube-proxy:8001']
    metrics_path: /api/v1/namespaces/default/services/health-app-service:8085/proxy/actuator/prometheus